from enum import Enum

class RejectReason(str, Enum):
    CYCLE_DETECTED = "CYCLE_DETECTED"
    MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
    ORPHAN_TASK = "ORPHAN_TASK"
    DUPLICATE_TASK_IDS = "DUPLICATE_TASK_IDS"

class RejectionType(str, Enum):
    PRIMARY_SPATIAL_VIOLATION = "PRIMARY_SPATIAL_VIOLATION"
    SECONDARY_DEPENDENCY_STARVATION = "SECONDARY_DEPENDENCY_STARVATION"
    SECONDARY_UPSTREAM_DEAD_END = "SECONDARY_UPSTREAM_DEAD_END"
